
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import '../../core/widgets/n_card.dart';
import '../../core/widgets/n_logo.dart';
import '../../app.dart';
class OnboardingScreen extends StatefulWidget { const OnboardingScreen({super.key}); @override State<OnboardingScreen> createState()=>_OnboardingScreenState(); }
class _OnboardingScreenState extends State<OnboardingScreen>{
  final _pc=PageController(); int _idx=0;
  final _data=[{'title':'مرحباً بك في نظام','desc':'Super App لإدارة حياتك بالكامل Offline-first','icon':'🚀'},{'title':'7 أنظمة متكاملة','desc':'مهام Kanban، مالية برسوم حقيقية، عادات، خزنة مشفرة','icon':'🧩'},{'title':'خصوصيتك أولاً','desc':'كل بياناتك Hive على جهازك، تشفير AES، وتصدير JSON','icon':'🔒'}];
  void _finish(){ Hive.box('settings').put('onboarding_seen', true); Navigator.pushReplacement(context, MaterialPageRoute(builder: (_)=>const MainShell())); }
  @override Widget build(BuildContext context){ return Scaffold(body: SafeArea(child: Column(children: [Expanded(child: PageView.builder(controller:_pc, onPageChanged:(i)=>setState(()=>_idx=i), itemCount:_data.length, itemBuilder: (_,i){ final d=_data[i]; return Padding(padding: const EdgeInsets.all(24), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Text(d['icon'] as String, style: const TextStyle(fontSize:80)), const SizedBox(height:24), NCard(child: Column(children: [const NLogo(size:64), const SizedBox(height:16), Text(d['title'] as String, style: const TextStyle(fontSize:24, fontWeight: FontWeight.w800), textAlign: TextAlign.center), const SizedBox(height:12), Text(d['desc'] as String, style: const TextStyle(fontSize:16, color:Colors.grey, height:1.6), textAlign: TextAlign.center)]))])) ;})), Row(mainAxisAlignment: MainAxisAlignment.center, children: List.generate(3, (i)=>Container(margin: const EdgeInsets.all(4), width:_idx==i?24:8, height:8, decoration: BoxDecoration(color:_idx==i? const Color(0xFF7C3AED): Colors.grey.shade300, borderRadius: BorderRadius.circular(8))))), const SizedBox(height:24), Padding(padding: const EdgeInsets.all(24), child: SizedBox(width:double.infinity, child: ElevatedButton(style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF7C3AED), foregroundColor: Colors.white, padding: const EdgeInsets.symmetric(vertical:16), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16))), onPressed:_idx==2? _finish: ()=>_pc.nextPage(duration: const Duration(milliseconds:300), curve: Curves.easeOut), child: Text(_idx==2?'ابدأ نظامك الآن':'التالي', style: const TextStyle(fontWeight: FontWeight.w800, fontSize:16)))))]))); }
}
