
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/widgets/n_card.dart';
import '../../../core/theme/app_colors.dart';
import '../../../data/models/app_models.dart';
import '../providers/task_provider.dart';
import 'kanban_screen.dart';
import 'task_detail_screen.dart';
class TasksListScreen extends ConsumerStatefulWidget { const TasksListScreen({super.key}); @override ConsumerState<TasksListScreen> createState()=>_TasksListScreenState(); }
class _TasksListScreenState extends ConsumerState<TasksListScreen>{
  String filter='all';
  @override Widget build(BuildContext context){
    final tasks=ref.watch(tasksProvider); final projects=ref.watch(projectsProvider);
    final filtered=tasks.where((t){ if(filter=='all') return true; return t.status==filter; }).toList();
    return Scaffold(body: Column(children: [Padding(padding: const EdgeInsets.all(16), child: Row(children:[Expanded(child: SingleChildScrollView(scrollDirection: Axis.horizontal, child: Row(children:[_chip('الكل','all'),_chip('مهام','todo'),_chip('قيد التنفيذ','doing'),_chip('منجزة','done')]))), IconButton(onPressed: ()=>Navigator.push(context, MaterialPageRoute(builder: (_)=>const KanbanScreen())), icon: const Icon(Icons.view_kanban_rounded, color: AppColors.primary))])), Expanded(child: filtered.isEmpty? const Center(child: Text('لا يوجد مهام')): ListView.builder(padding: const EdgeInsets.fromLTRB(16,0,16,100), itemCount: filtered.length, itemBuilder: (_,i){ final t=filtered[i]; final proj=projects.where((p)=>p.id==t.projectId).isEmpty?null:projects.firstWhere((p)=>p.id==t.projectId); return Padding(padding: const EdgeInsets.only(bottom:12), child: NCard(onTap: ()=>Navigator.push(context, MaterialPageRoute(builder: (_)=>TaskDetailScreen(task:t))), child: Row(children:[Container(width:4,height:48,decoration: BoxDecoration(color: t.status=='done'? AppColors.secondary: t.status=='doing'? AppColors.warning: AppColors.primary, borderRadius: BorderRadius.circular(4))), const SizedBox(width:12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children:[Text(t.title, style: TextStyle(fontWeight: FontWeight.w800, decoration: t.status=='done'? TextDecoration.lineThrough:null)), const SizedBox(height:4), Row(children:[if(proj!=null) Container(padding: const EdgeInsets.symmetric(horizontal:8, vertical:2), decoration: BoxDecoration(color: AppColors.primary.withOpacity(0.1), borderRadius: BorderRadius.circular(8)), child: Text(proj.name, style: const TextStyle(fontSize:11, color:AppColors.primary))), const SizedBox(width:6), Text('\${t.pomodoroCount} 🍅', style: const TextStyle(fontSize:11, color:Colors.grey))])])), Checkbox(value: t.status=='done', activeColor:AppColors.primary, onChanged:(v){ ref.read(tasksProvider.notifier).updateStatus(t.id, v!?'done':'todo');})]))); }))]), floatingActionButton: FloatingActionButton.extended(backgroundColor:AppColors.primary, foregroundColor:Colors.white, onPressed: ()=>_addDialog(), icon: const Icon(Icons.add), label: const Text('مهمة جديدة')));
  }
  Widget _chip(String l,String v){ final sel=filter==v; return Padding(padding: const EdgeInsets.only(left:6), child: ChoiceChip(label: Text(l), selected:sel, selectedColor:AppColors.primary, labelStyle: TextStyle(color: sel? Colors.white: Colors.black87, fontWeight: FontWeight.w700), onSelected: (_)=>setState(()=>filter=v))); }
  void _addDialog(){ final ctrl=TextEditingController(); String? selProj=ref.read(projectsProvider).isEmpty? null: ref.read(projectsProvider).first.id; showDialog(context: context, builder: (_)=> AlertDialog(title: const Text('مهمة جديدة'), content: Column(mainAxisSize:MainAxisSize.min, children:[TextField(controller:ctrl, decoration: const InputDecoration(hintText:'عنوان المهمة', border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))))), const SizedBox(height:12), DropdownButtonFormField<String>(value:selProj, decoration: const InputDecoration(border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12)))), items: ref.read(projectsProvider).map((p)=>DropdownMenuItem(value:p.id, child: Text(p.name))).toList(), onChanged:(v)=>selProj=v)]), actions:[TextButton(onPressed: ()=>Navigator.pop(context), child: const Text('إلغاء')), ElevatedButton(style: ElevatedButton.styleFrom(backgroundColor:AppColors.primary, foregroundColor:Colors.white), onPressed:(){ if(ctrl.text.trim().isEmpty|| selProj==null) return; ref.read(tasksProvider.notifier).add(TaskModel.create(title:ctrl.text.trim(), projectId:selProj!)); Navigator.pop(context); }, child: const Text('إضافة'))])); }
}
