import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:table_calendar/table_calendar.dart';
import 'package:uuid/uuid.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../core/storage.dart';
import '../../core/models.dart';
import '../../core/theme.dart';
import '../../providers/app_provider.dart';
import '../../services/vault.dart';
import '../../services/notifications.dart';
import '../widgets/common.dart';

class SplashScreen extends StatefulWidget{const SplashScreen({super.key});@override State<SplashScreen> createState()=>_Splash();}
class _Splash extends State<SplashScreen>{@override void initState(){super.initState();Future.delayed(const Duration(milliseconds:900),(){if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const OnboardingScreen()));});}@override Widget build(c)=>Scaffold(body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[_Logo(),const SizedBox(height:18),Text('Nizam OS',style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),const CircularProgressIndicator()]));}
class _Logo extends StatelessWidget{const _Logo();@override Widget build(c)=>Container(width:86,height:86,decoration:BoxDecoration(shape:BoxShape.circle,color:AppTheme.purple),child:const Center(child:Text('ن',style:TextStyle(color:Colors.white,fontSize:48,fontWeight:FontWeight.bold))));}
class OnboardingScreen extends StatefulWidget{const OnboardingScreen({super.key});@override State<OnboardingScreen> createState()=>_Onb();}
class _Onb extends State<OnboardingScreen>{final p=PageController();int i=0;final pages=[('نظامك الشخصي','إدارة المهام والمال والعادات والمعرفة في مكان واحد.'),('خصوصيتك أولاً','بياناتك محلية ومشفرة، ولا تحتاج إلى Firebase.'),('ابدأ الآن','ابنِ يومك حول أهدافك وبياناتك الحقيقية.')];@override Widget build(c)=>Scaffold(body:SafeArea(child:Column(children:[Expanded(child:PageView.builder(controller:p,itemCount:3,onPageChanged:(x)=>setState(()=>i=x),itemBuilder:(c,x)=>Center(child:Padding(padding:const EdgeInsets.all(30),child:Column(mainAxisSize:MainAxisSize.min,children:[_Logo(),const SizedBox(height:30),Text(pages[x].$1,style:Theme.of(c).textTheme.headlineMedium,textAlign:TextAlign.center),const SizedBox(height:12),Text(pages[x].$2,textAlign:TextAlign.center)]))))),Row(mainAxisAlignment:MainAxisAlignment.center,children:List.generate(3,(x)=>Container(width:9,height:9,margin:const EdgeInsets.all(4),decoration:BoxDecoration(shape:BoxShape.circle,color:x==i?AppTheme.purple:Colors.grey)))),Padding(padding:const EdgeInsets.all(24),child:SizedBox(width:double.infinity,child:NButton(label:i==2?'دخول Nizam OS':'التالي',onTap:()=>i==2?Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const Shell())):p.nextPage(duration:const Duration(milliseconds:250),curve:Curves.easeOut))))]));}}
class Shell extends StatefulWidget{const Shell({super.key});@override State<Shell> createState()=>_Shell();}
class _Shell extends State<Shell>{int index=0;final pages=const [DashboardScreen(),TasksScreen(),FinanceScreen(),HabitsScreen(),SettingsScreen()];@override Widget build(c)=>Scaffold(body:pages[index],bottomNavigationBar:Padding(padding:const EdgeInsets.fromLTRB(10,0,10,10),child:GlassNav(index:index,onTap:(i)=>setState(()=>index=i))));}

class DashboardScreen extends ConsumerWidget{const DashboardScreen({super.key});@override Widget build(c,ref){final tasks=ref.watch(tasksProvider);final balance=ref.watch(financeProvider);final done=tasks.where((x)=>x.done).length;return SafeArea(child:CustomScrollView(slivers:[SliverPadding(padding:const EdgeInsets.all(18),sliver:SliverToBoxAdapter(child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('مساء الخير 👋',style:Theme.of(c).textTheme.titleMedium),Text('Nizam OS',style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800))]),_Logo()]))),SliverPadding(padding:const EdgeInsets.fromLTRB(18,18,18,0),sliver:SliverGrid(delegate:SliverChildListDelegate([_Stat('المهام', '${done}/${tasks.length}',LucideIcons.checkCircle),_Stat('الرصيد',balance.toStringAsFixed(2),LucideIcons.wallet),_Stat('العادات','0',LucideIcons.flame),_Stat('الإنتاجية',tasks.isEmpty?'0%':'${(done*100/tasks.length).round()}%',LucideIcons.trendingUp)]),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.45))),SliverPadding(padding:const EdgeInsets.all(18),sliver:SliverToBoxAdapter(child:NCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('مهام اليوم',style:Theme.of(c).textTheme.titleLarge),const SizedBox(height:12),if(tasks.isEmpty)const Text('لا توجد مهام بعد.'),...tasks.take(5).map((t)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(t.title),leading:Icon(t.done?LucideIcons.checkCircle2:LucideIcons.circle,color:t.done?AppTheme.green:null)))])))),SliverPadding(padding:const EdgeInsets.fromLTRB(18,0,18,30),sliver:SliverToBoxAdapter(child:NCard(child:SizedBox(height:170,child:LineChart(LineChartData(gridData:const FlGridData(show:false),titlesData:const FlTitlesData(show:false),borderData:FlBorderData(show:false),lineBarsData:[LineChartBarData(isCurved:true,barWidth:3,dotData:const FlDotData(show:false),spots:const [FlSpot(0,2),FlSpot(1,3),FlSpot(2,2),FlSpot(3,4),FlSpot(4,3),FlSpot(5,5),FlSpot(6,4)])])))))]));}}
class _Stat extends StatelessWidget{final String a,b;final IconData icon;const _Stat(this.a,this.b,this.icon);@override Widget build(c)=>NCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:AppTheme.purple),const Spacer(),Text(b,style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),Text(a)]));}

class TasksScreen extends ConsumerWidget{const TasksScreen({super.key});@override Widget build(c,ref){final tasks=ref.watch(tasksProvider);return Scaffold(appBar:AppBar(title:const Text('Task OS'),actions:[IconButton(onPressed:()=>_add(c,ref),icon:const Icon(LucideIcons.plus))]),body:ListView(padding:const EdgeInsets.all(18),children:[for(final status in ['todo','doing','done'])NCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(status=='todo'?'To Do':status=='doing'?'Doing':'Done',style:Theme.of(c).textTheme.titleLarge),...tasks.where((t)=>t.status==status).map((t)=>ListTile(title:Text(t.title),subtitle:Text(t.project),leading:Checkbox(value:t.done,onChanged:(_)=>ref.read(tasksProvider.notifier).toggle(t)),trailing:PopupMenuButton<String>(onSelected:(s)=>ref.read(tasksProvider.notifier).move(t,s),itemBuilder:(_)=>const [PopupMenuItem(value:'todo',child:Text('To Do')),PopupMenuItem(value:'doing',child:Text('Doing')),PopupMenuItem(value:'done',child:Text('Done'))])))])),const SizedBox(height:12)]));}}
void _add(BuildContext c,WidgetRef ref){final ctl=TextEditingController();showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('مهمة جديدة'),content:TextField(controller:ctl,autofocus:true,decoration:const InputDecoration(hintText:'عنوان المهمة')),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إلغاء')),FilledButton(onPressed:()async{if(ctl.text.trim().isNotEmpty)await ref.read(tasksProvider.notifier).add(ctl.text.trim());if(c.mounted)Navigator.pop(c);},child:const Text('حفظ'))]));}

class FinanceScreen extends ConsumerStatefulWidget{const FinanceScreen({super.key});@override ConsumerState<FinanceScreen> createState()=>_Fin();}
class _Fin extends ConsumerState<FinanceScreen>{String type='expense';@override Widget build(c){final b=Storage.box('transactions');final values=b.values.map((e)=>Map<String,dynamic>.from(e as Map)).toList();final income=values.where((m)=>m['type']=='income').fold<double>(0,(s,m)=>s+(m['amount'] as num).toDouble());final expense=values.where((m)=>m['type']=='expense').fold<double>(0,(s,m)=>s+(m['amount'] as num).toDouble());return Scaffold(appBar:AppBar(title:const Text('Finance OS'),actions:[IconButton(onPressed:()=>_addTx(c),icon:const Icon(LucideIcons.plus))]),body:ListView(padding:const EdgeInsets.all(18),children:[NCard(child:Column(children:[Text('الرصيد الحقيقي',style:Theme.of(c).textTheme.titleMedium),Text((income-expense).toStringAsFixed(2),style:Theme.of(c).textTheme.displaySmall?.copyWith(fontWeight:FontWeight.bold)),SizedBox(height:180,child:PieChart(PieChartData(sections:[PieChartSectionData(value:income,title:'دخل'),PieChartSectionData(value:expense,title:'مصروف')])))])),const SizedBox(height:12),NCard(child:Column(children:[Text('المعاملات',style:Theme.of(c).textTheme.titleLarge),...values.reversed.take(20).map((m)=>ListTile(title:Text(m['title']),subtitle:Text(m['type']),trailing:Text('${m['amount']}')))]))]);}
Future<void> _addTx(BuildContext c)async{final title=TextEditingController();final amount=TextEditingController();await showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('معاملة'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,decoration:const InputDecoration(labelText:'الوصف')),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'المبلغ')),DropdownButton<String>(value:type,items:const [DropdownMenuItem(value:'expense',child:Text('مصروف')),DropdownMenuItem(value:'income',child:Text('دخل'))],onChanged:(v)=>setState(()=>type=v!))]),actions:[FilledButton(onPressed:()async{final a=double.tryParse(amount.text);if(title.text.isNotEmpty&&a!=null){await Storage.box('transactions').put(const Uuid().v4(),{'title':title.text,'amount':a,'type':type,'date':DateTime.now().toIso8601String()});setState((){});}if(c.mounted)Navigator.pop(c);},child:const Text('حفظ'))]));}}
class HabitsScreen extends ConsumerStatefulWidget{const HabitsScreen({super.key});@override ConsumerState<HabitsScreen> createState()=>_Habits();}
class _Habits extends ConsumerState<HabitsScreen>{@override Widget build(c){final h=Storage.box('habits');final habits=h.values.map((e)=>Map<String,dynamic>.from(e as Map)).toList();return Scaffold(appBar:AppBar(title:const Text('Habit OS')),body:ListView(padding:const EdgeInsets.all(18),children:[NCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('عاداتك',style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:12),if(habits.isEmpty)const Text('أضف أول عادة لتبدأ.'),...habits.map((m)=>ListTile(title:Text(m['name']),leading:const Icon(LucideIcons.flame),trailing:Text('🔥 ${m['streak']??0}'))),NButton(label:'إضافة عادة',onTap:()=>_add(c))])),const SizedBox(height:12),NCard(child:Column(children:[const Text('الصلوات الخمس'),for(final p in ['الفجر','الظهر','العصر','المغرب','العشاء'])CheckboxListTile(value:false,onChanged:(_){},title:Text(p))])),const SizedBox(height:12),NCard(child:Column(children:[const Text('ماء ونوم'),ListTile(title:const Text('الماء'),trailing:Text('${Storage.box('water').get('today',defaultValue:0)} كوب')),ListTile(title:const Text('النوم'),trailing:Text('${Storage.box('sleep').get('last',defaultValue:0)} ساعة'))]))]);}
Future<void> _add(BuildContext c)async{final t=TextEditingController();await showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('عادة'),content:TextField(controller:t,decoration:const InputDecoration(hintText:'اسم العادة')),actions:[FilledButton(onPressed:()async{if(t.text.trim().isNotEmpty)await Storage.box('habits').put(const Uuid().v4(),{'name':t.text.trim(),'streak':0,'createdAt':DateTime.now().toIso8601String()});if(c.mounted){Navigator.pop(c);setState((){});}},child:const Text('حفظ'))]));}}
class VaultScreen extends StatefulWidget{const VaultScreen({super.key});@override State<VaultScreen> createState()=>_Vault();}
class _Vault extends State<VaultScreen>{bool unlocked=false;@override void initState(){super.initState();_unlock();}Future<void> _unlock()async{final ok=await VaultService.unlock();if(mounted)setState(()=>unlocked=ok);} @override Widget build(c){final b=Storage.box('vault');final vals=b.values.map((e)=>Map<String,dynamic>.from(e as Map)).toList();return Scaffold(appBar:AppBar(title:const Text('Vault OS')),body:unlocked?ListView(padding:const EdgeInsets.all(18),children:[...vals.map((m)=>NCard(child:ListTile(title:Text(m['title']),subtitle:Text(m['secret'])))),NButton(label:'إضافة سر',onTap:()=>_add(c))]):Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(LucideIcons.lockKeyhole,size:64),const SizedBox(height:12),const Text('الخزنة مقفلة'),NButton(label:'فتح بالبصمة',onTap:_unlock)]));}Future<void>_add(BuildContext c)async{final a=TextEditingController(),s=TextEditingController();await showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('سر جديد'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:a,decoration:const InputDecoration(labelText:'العنوان')),TextField(controller:s,obscureText:true,decoration:const InputDecoration(labelText:'المحتوى'))]),actions:[FilledButton(onPressed:()async{await VaultService.put(a.text,s.text);if(c.mounted){Navigator.pop(c);setState((){});}},child:const Text('حفظ'))]));}}
class GoalsScreen extends StatelessWidget{const GoalsScreen({super.key});@override Widget build(c)=>_Simple(title:'Goals & Journal',icon:LucideIcons.target,body:TableCalendar(firstDay:DateTime.utc(2020),lastDay:DateTime.utc(2035),focusedDay:DateTime.now()));}
class SearchScreen extends StatefulWidget{const SearchScreen({super.key});@override State<SearchScreen> createState()=>_Search();}
class _Search extends State<SearchScreen>{String q='';@override Widget build(c){final results=<Map<String,dynamic>>[];for(final name in ['tasks','notes','goals','journal'])for(final v in Storage.box(name).values){if(v is Map && q.isNotEmpty && v.values.any((x)=>x.toString().toLowerCase().contains(q.toLowerCase())))results.add(Map<String,dynamic>.from(v));}return Scaffold(appBar:AppBar(title:const Text('Global Search')),body:Column(children:[Padding(padding:const EdgeInsets.all(16),child:TextField(onChanged:(v)=>setState(()=>q=v),decoration:const InputDecoration(prefixIcon:Icon(LucideIcons.search),hintText:'ابحث في كل شيء'))),Expanded(child:ListView(children:results.map((m)=>ListTile(title:Text(m['title']?.toString()??'عنصر'),subtitle:Text(m.values.join(' • '))).toList())))]);}}
class SettingsScreen extends StatefulWidget{const SettingsScreen({super.key});@override State<SettingsScreen> createState()=>_Settings();}
class _Settings extends State<SettingsScreen>{@override Widget build(c)=>Scaffold(appBar:AppBar(title:const Text('الإعدادات')),body:ListView(padding:const EdgeInsets.all(18),children:[NCard(child:Column(children:[SwitchListTile(title:const Text('الوضع الداكن'),value:Theme.of(c).brightness==Brightness.dark,onChanged:(v)=>setState((){})),ListTile(leading:const Icon(LucideIcons.lock),title:const Text('Vault OS'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const VaultScreen()))),ListTile(leading:const Icon(LucideIcons.target),title:const Text('الأهداف والمفكرة'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const GoalsScreen()))),ListTile(leading:const Icon(LucideIcons.search),title:const Text('البحث الشامل'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const SearchScreen()))),ListTile(leading:const Icon(LucideIcons.download),title:const Text('نسخة JSON'),onTap:()async{final json=await Storage.exportJson();if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('تم تجهيز ${json.length} حرفًا من البيانات المحلية')));})]))]));}}
class _Simple extends StatelessWidget{final String title;final IconData icon;final Widget body;const _Simple({required this.title,required this.icon,required this.body});@override Widget build(c)=>Scaffold(appBar:AppBar(title:Text(title)),body:Padding(padding:const EdgeInsets.all(18),child:NCard(child:Column(children:[Icon(icon,size:50,color:AppTheme.purple),const SizedBox(height:12),Expanded(child:body)]))));}

class TaskDetailScreen extends StatelessWidget{final Task task;const TaskDetailScreen({super.key,required this.task});@override Widget build(c)=>_Simple(title:'تفاصيل المهمة',icon:LucideIcons.checkSquare,body:ListView(children:[Text(task.title,style:Theme.of(c).textTheme.headlineSmall),Text('المشروع: ${task.project.isEmpty?'بدون مشروع':task.project}'),Text('الحالة: ${task.status}'),const SizedBox(height:20),NButton(label:'Pomodoro 25 دقيقة',onTap:()=>_pomodoro(c))]));}
void _pomodoro(BuildContext c){var left=25*60;Timer? timer;showDialog(context:c,builder:(_){return StatefulBuilder(builder:(c,set){timer??=Timer.periodic(const Duration(seconds:1),(_){if(left>0)set(()=>left--);});return AlertDialog(title:const Text('Pomodoro'),content:Text('${left~/60}:${(left%60).toString().padLeft(2,'0')}',style:Theme.of(c).textTheme.displayMedium),actions:[TextButton(onPressed:(){timer?.cancel();Navigator.pop(c);},child:const Text('إيقاف'))]);});}).then((_){timer?.cancel();});}
class WalletsScreen extends StatelessWidget{const WalletsScreen({super.key});@override Widget build(c)=>_BoxList(title:'Wallets',box:'wallets',label:'محفظة');}
class BudgetsScreen extends StatelessWidget{const BudgetsScreen({super.key});@override Widget build(c)=>_BoxList(title:'Budgets',box:'budgets',label:'ميزانية');}
class DebtsScreen extends StatelessWidget{const DebtsScreen({super.key});@override Widget build(c)=>_BoxList(title:'Debts',box:'debts',label:'دين');}
class PrayerScreen extends StatelessWidget{const PrayerScreen({super.key});@override Widget build(c)=>Scaffold(appBar:AppBar(title:const Text('متتبع الصلاة')),body:ListView(padding:const EdgeInsets.all(18),children:[NCard(child:Column(children:[for(final p in ['الفجر','الظهر','العصر','المغرب','العشاء'])CheckboxListTile(value:false,onChanged:(_){},title:Text(p))]))]));}
class JournalScreen extends StatelessWidget{const JournalScreen({super.key});@override Widget build(c)=>Scaffold(appBar:AppBar(title:const Text('المفكرة')),body:ListView(padding:const EdgeInsets.all(18),children:[NCard(child:TableCalendar(firstDay:DateTime.utc(2020),lastDay:DateTime.utc(2035),focusedDay:DateTime.now())),const SizedBox(height:12),NCard(child:const TextField(maxLines:8,decoration:InputDecoration(hintText:'اكتب يومياتك...')))]);}
class StatisticsScreen extends ConsumerWidget{const StatisticsScreen({super.key});@override Widget build(c,ref){final t=ref.watch(tasksProvider);final d=t.where((x)=>x.done).length;return _Simple(title:'Statistics',icon:LucideIcons.barChart3,body:ListView(children:[Text('إنجاز المهام: ${t.isEmpty?0:(d*100/t.length).round()}%'),const SizedBox(height:20),SizedBox(height:220,child:BarChart(BarChartData(barGroups:[BarChartGroupData(x:0,barRods:[BarChartRodData(toY:d.toDouble())]),BarChartGroupData(x:1,barRods:[BarChartRodData(toY:(t.length-d).toDouble())])]))))]));}}
class NotesScreen extends StatefulWidget{const NotesScreen({super.key});@override State<NotesScreen> createState()=>_Notes();}
class _Notes extends State<NotesScreen>{@override Widget build(c){final b=Storage.box('notes');return Scaffold(appBar:AppBar(title:const Text('Knowledge'),actions:[IconButton(onPressed:()=>_add(c),icon:const Icon(LucideIcons.plus))]),body:ListView(padding:const EdgeInsets.all(18),children:b.values.map((e){final m=Map<String,dynamic>.from(e as Map);return NCard(child:ListTile(title:Text(m['title']??''),subtitle:Text(m['body']??'')));}).toList());}Future<void>_add(BuildContext c)async{final t=TextEditingController(),b=TextEditingController();await showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('ملاحظة'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:t,decoration:const InputDecoration(labelText:'العنوان')),TextField(controller:b,maxLines:4,decoration:const InputDecoration(labelText:'النص'))]),actions:[FilledButton(onPressed:()async{await Storage.box('notes').put(const Uuid().v4(),{'title':t.text,'body':b.text,'date':DateTime.now().toIso8601String()});if(c.mounted){Navigator.pop(c);setState((){});}},child:const Text('حفظ'))]));}}
class _BoxList extends StatelessWidget{final String title,box,label;const _BoxList({required this.title,required this.box,required this.label});@override Widget build(c){final b=Storage.box(box);return Scaffold(appBar:AppBar(title:Text(title)),body:ListView(padding:const EdgeInsets.all(18),children:[...b.values.map((e){final m=Map<String,dynamic>.from(e as Map);return NCard(child:ListTile(title:Text(m['name']??label),subtitle:Text(m['amount']?.toString()??'')));}),NButton(label:'إضافة $label',onTap:()async{await b.put(const Uuid().v4(),{'name':label,'amount':0,'createdAt':DateTime.now().toIso8601String()});})]));}}
